
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: john
    password: john

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
